### ISSUE TITLE
Examples don't work in IE11, Firefox or Safari

### ISSUE THREAD

**Issue by emrul** [kotojs/kotojs#10]
Hi,

I really like the idea of Koto and am looking into it in more detail.  I noticed that the 2 examples only work under Chrome - Firefox, Safari and IE seem to be left in the cold.

I know Babel is a great transpiler and the solution is to use it when using KotoJS but shouldn't it be used for the samples?

**Comment by nicksrandall** [comment]
Yes, I have always intended that users would use a transpiler when using KotoJS in production. I didn't transpile the code in the examples because I wanted users to be able to see the code as they would write it and not as it would be transpiled. 

I understand that this could be confusing so I've switched the examples to use JSBIN which has an auto-transpile feature (using babel).

Thanks for your feedback!

**Comment by emrul** [comment]
Thanks Nick!  Much more accessible now to users who casually find this toolkit.

We'll be delving into it in the week ahead, potentially transforming some of our d3 work to it and see how we get on.
